# Generated by Django 5.2.1 on 2025-06-11 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_venue_description_venue_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Musician', 'verbose_name_plural': 'Musicians'},
        ),
        migrations.AddField(
            model_name='musician',
            name='bio_pic',
            field=models.ImageField(blank=True, help_text='Profile picture of the musician', null=True, upload_to='musicians/bio_pics/'),
        ),
        migrations.AddField(
            model_name='musician',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True, help_text='A brief biography of the musician', null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='user_profile',
            field=models.ForeignKey(blank=True, help_text='The user profile that owns this musician record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicians', to='bands.userprofile'),
        ),
    ]
